# Generated by Django 5.0.6 on 2024-05-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rentings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentings',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
